[project]
name = "mcp-thing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.4",
    "pandas>=2.3.0",
    "statsmodels>=0.14.4",
]
